name: Actualizar Calendario ICS

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 👈 ESTA LÍNEA CONCEDE PERMISOS DE ESCRITURA EN EL REPOSITORIO
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6 

      - name: Configurar Node.js
        uses: actions/setup-node@v6 
        with:
          node-version: '24' 

      - name: Ejecutar script generador
        run: node generar.js

      - name: Subir cambios al alojamiento estático
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add agenda.ics
          git diff-index --quiet HEAD || git commit -m "Auto: Actualización de la agenda cultural"
          git push
